services:
  - type: web
    name: kira-imports-backend
    runtime: node
    repo: https://github.com/hassanrotich111-source/kiraimports-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Wv3zK6PRrHLN@ep-flat-lab-am9hcpje.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: kira_imports_secret_key_2024_secure
      - key: CLOUDINARY_CLOUD_NAME
        value: dc71005wj
      - key: CLOUDINARY_API_KEY
        value: 655581152523785
      - key: CLOUDINARY_API_SECRET
        value: _jowO0DwPzE-xsOIfid4TQeZdwA
      - key: NODE_VERSION
        value: 18
